name: recipes_cook
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4  # Adjust based on your Flutter version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  get: ^4.6.5
  dartz: ^0.10.1
  get_storage: ^2.1.1
  http: ^0.13.6
  sqflite: ^2.3.0
  responsive_framework: ^0.2.0
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  flutter_animate: ^4.2.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/